version: '2'

networks:
  app-tier:
    driver: bridge

services:
  spotweb:
    image: 'jbaten/spotweb:0.9.6'
    environment:
      - DB_ENGINE=pdo_mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=mini
      - DB_USER=mini
      - DB_PASSWORD=mini
      - DB_SCHEMA=public
      - SPOTWEB_SYSTEMTYPE=public
      - SPOTWEB_USERNAME=myawesomeuser
      - SPOTWEB_PASSWORD=demo123
      - SPOTWEB_FIRSTNAME=demo
      - SPOTWEB_LASTNAME=spotweb
      - SPOTWEB_MAIL=demo@spotweb.com
    networks:
      - app-tier
    ports:
      - '9080:80'
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_USER=mini
        - MARIADB_PASSWORD=mini
        - MARIADB_DATABASE=mini
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
